# Generated by Django 5.2.9 on 2026-01-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('availability_status', models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'Offline'), ('b', 'Break')], default='a', help_text='is this mongopack available, offline, or he took a break', max_length=1)),
            ],
        ),
    ]
